/*
  # YeBetWeg Seed Data

  Populates all tables with realistic Ethiopian construction context data.

  1. Blogs: 8 articles covering construction techniques, philosophy, market insights, regulations, materials
  2. Tips: 10 tips (6 free, 4 premium) on structural, finishing, foundation, waterproofing topics
  3. Market Prices: 15 materials with realistic Addis Ababa 2024 prices
  4. Listings: 12 listings (5 properties, 4 materials, 3 professional services)
  5. Professionals: 6 verified construction professionals
  6. Ads: 3 mock advertisements
*/

-- Blog seed data
INSERT INTO blogs (title_am, title_en, content, category, image_url, author, slug, is_featured) VALUES
('ለአዲስ አበባ የመከላከያ ዞን የራብር ዓይነት መምረጫ', 'Rebar Grade Selection for Addis Ababa Seismic Zone', 'When building in Addis Ababa, understanding seismic requirements is critical. The Ethiopian Building Code EBCS-8 mandates specific rebar grades for different structural elements. For columns in G+5 structures, Grade 60 (420 MPa yield strength) rebar is the minimum requirement. This article covers the complete rebar selection process, from understanding Ethiopian standards to sourcing quality steel from local suppliers in the Merkato industrial zone. We also discuss the common practice of mixing Grade 40 and Grade 60 rebar and why this should be avoided in seismic zones.', 'construction_techniques', '/blog/rebar-selection.jpg', 'Eng. Dawit Amare', 'rebar-grade-selection-addis', true),
('ለ G+5 ህንፃዎች የኢትዮጵያ የግንባታ ደንብ ቅያር', 'Ethiopian Building Code Compliance for G+5 Structures', 'The Ethiopian Building Code Standards (EBCS) provide comprehensive guidelines for multi-story construction. This guide walks through the key compliance requirements for G+5 structures in Addis Ababa, including foundation depth requirements (minimum 1.5m below frost line), concrete mix ratios (1:2:4 for C-25), and the mandatory structural review process. We also cover the recent updates to EBCS-8 that affect seismic design categories for the Rift Valley region.', 'regulations', '/blog/ebcs-compliance.jpg', 'Arch. Tigist Haile', 'ethiopian-building-code-g5', false),
('ቤት መሥራት ሰብዓዊ ተግባር ነው', 'Building as a Human Act: The Philosophy of Ethiopian Architecture', 'In Ethiopian tradition, building a home is not merely construction — it is a communal act that binds neighbors and generations. The practice of "Gebeta Legebete" (mutual aid in construction) reflects a philosophy where every structure carries the spirit of its community. This article explores how modern Ethiopian architects are integrating this philosophy into contemporary designs, from the use of local stone in Lalibela-inspired facades to the incorporation of traditional "Tukul" spatial concepts in urban housing developments.', 'philosophy', '/blog/building-philosophy.jpg', 'Dr. Mulugeta Tessema', 'building-human-act-philosophy', true),
('2024 የአዲስ አበባ የሲሚንቶ ገበያ አጠቃላይ እይታ', 'Addis Ababa Cement Market Overview 2024', 'The cement market in Addis Ababa has seen significant fluctuations in 2024. Derba Cement remains the market leader at 8,200 ETB per ton, while Mugher Cement has increased prices by 12% due to rising energy costs. This comprehensive overview covers all major brands, their current pricing, quality comparisons based on compressive strength tests, and practical advice on when to use OPC versus PPC cement for different construction phases. We also analyze the impact of the new Dangote plant expansion on market dynamics.', 'market_insights', '/blog/cement-market.jpg', 'YeBetWeg Market Team', 'cement-market-overview-2024', false),
('የውሃ መከላከያ ስራዎች ለአዲስ አበባ ክላይሜት የላብራቶሪ ውጤቶች', 'Waterproofing Solutions for Addis Ababa Climate: Lab Results', 'Addis Ababa receives over 1,200mm of rainfall annually, with the Keremt season (June-September) bringing intense downpours. This article presents laboratory test results comparing 8 waterproofing products available in the Ethiopian market. We tested membrane systems, crystalline coatings, and liquid-applied membranes under simulated Ethiopian rainfall conditions. Key findings: crystalline coatings (like Xypex) perform best for basement walls, while modified bitumen membranes are most cost-effective for roof decks.', 'materials', '/blog/waterproofing-lab.jpg', 'Eng. Sara Kebede', 'waterproofing-lab-results', false),
('የኮንክሪት ማንሻ ምርጥ ልምዶች', 'Concrete Mixing Best Practices for Ethiopian Conditions', 'The quality of concrete in Ethiopian construction varies dramatically due to inconsistent mixing practices. This guide covers the critical factors: water-cement ratio (0.45-0.50 for C-25), aggregate grading (using Awash River sand requires different proportions than crushed sand), and the impact of Addis Ababa altitude on curing time. We provide practical mixing tables for common concrete grades and explain why the "eye-balling" method common on Ethiopian sites leads to 30% strength reduction.', 'construction_techniques', '/blog/concrete-mixing.jpg', 'Eng. Dawit Amare', 'concrete-mixing-best-practices', false),
('የኢትዮጵያ የንብረት ገበያ አዝማሚያዎች 2024', 'Ethiopian Property Market Trends 2024', 'The Ethiopian property market continues to evolve rapidly in 2024. Land prices in prime Addis Ababa locations (Bole, CMC, Kazanchis) have increased 25-35% year-over-year, while emerging areas (Lebu, Ayat, Summit) offer more accessible entry points. This analysis covers price per square meter trends, the impact of the new housing development policies, and predictions for the rental market as the city expands. We also examine how the shift toward G+10 and taller buildings is reshaping the skyline and creating new investment opportunities.', 'market_insights', '/blog/property-trends.jpg', 'YeBetWeg Market Team', 'property-market-trends-2024', false),
('የተለያዩ የሲሚንቶ ዓይነቶች እና አጠቃቀማቸው', 'Cement Types and Their Applications in Ethiopian Construction', 'Understanding the difference between OPC (Ordinary Portland Cement) and PPC (Pozzolana Portland Cement) is essential for any construction project in Ethiopia. OPC provides faster early strength and is ideal for structural elements, while PPC offers better long-term durability and resistance to chemical attack — important for Addis Ababa soil conditions. This guide covers all cement types available in the Ethiopian market, their proper applications, and how to verify quality through simple field tests like the float test and date checking.', 'materials', '/blog/cement-types.jpg', 'Arch. Tigist Haile', 'cement-types-applications', false)
ON CONFLICT (slug) DO NOTHING;

-- Tips seed data
INSERT INTO tips (title_am, title_en, content, category, is_premium, icon) VALUES
('የራብር ደረጃዎች ምርጫ', 'Rebar Grade Selection: Always Verify Grade Markings', 'Before purchasing rebar, always check for grade markings. Grade 40 rebar has a single longitudinal rib, while Grade 60 has two. In the Ethiopian market, some suppliers mix grades — always request mill test certificates. Using Grade 40 where Grade 60 is specified can reduce structural capacity by 40%.', 'structural', false, 'shield'),
('የሲሚንቶ ጥራት ማረጋገጫ', 'Cement Quality Check: The Float Test', 'To quickly test cement quality at the site: throw a small handful of cement into a bucket of water. Good cement should float for a few seconds before sinking. If it sinks immediately, it has absorbed moisture and lost strength. Also check the manufacturing date — cement older than 3 months loses approximately 20% strength.', 'structural', false, 'flask-conical'),
('የኮንክሪት ማፅያ ጊዜ', 'Curing Time: Minimum 7 Days for Structural Concrete', 'In Addis Ababa altitude and climate, structural concrete requires minimum 7 days of wet curing. The first 24 hours are critical — cover with wet burlap or plastic sheeting. Reducing curing time from 7 to 3 days can result in 25% strength loss. For columns and beams, extend to 14 days for optimal strength development.', 'structural', false, 'clock'),
('የመሠረት ጥልቀት ማረጋገጫ', 'Foundation Depth: Check Soil Before You Dig', 'Before starting foundation work, always conduct a soil investigation. In Addis Ababa, the red clay soil (locally called "Lebm") can expand up to 15% when wet. Minimum foundation depth should be 1.2m, but in expansive soil areas (like CMC and Ayat), go to 1.8m with proper moisture barriers.', 'foundation', false, 'arrow-down-to-line'),
('የፕላስተር ድምር ምርጥ አጠቃቀም', 'Plastering Mix Ratio: 1:4 for External Walls', 'For external wall plastering in Addis Ababa, use a 1:4 cement-to-sand ratio. Internal walls can use 1:6. Always use clean, washed river sand. Adding a waterproofing admixture (1% by weight of cement) to external plaster significantly reduces water penetration during Keremt season.', 'finishing', false, 'paintbrush'),
('የውሃ መከላከያ መሠረታዊ እርምጃዎች', 'Waterproofing Basics: Start from Foundation', 'The most effective waterproofing strategy starts at the foundation. Apply a crystalline waterproofing coating to foundation walls before backfilling. For roof decks, use a minimum 2mm modified bitumen membrane with proper slope (minimum 1.5%). Never skip the waterproofing layer to save costs — water damage repair costs 5-10x the original waterproofing expense.', 'waterproofing', false, 'droplets'),
('የኤሌክትሪክ ስርዓት ዲዛይን ምርጥ ልምዶች', 'Electrical System Design: Plan for Future Expansion', 'When designing electrical systems for Ethiopian homes, plan for 30% future expansion capacity. Use minimum 2.5mm² wire for general circuits and 4mm² for kitchen and bathroom circuits. Install conduit pipes in all walls during construction — retrofitting conduit in finished walls costs 3x more. Consider solar-ready wiring on the roof for future panel installation.', 'electrical', true, 'zap'),
('የቧንቧ ስርዓት ዲዛይን ምርጥ ልምዶች', 'Plumbing System Design: Water Pressure Management', 'In Addis Ababa, municipal water pressure varies significantly. Install a pressure tank (minimum 200L) and booster pump system. Use PPR pipes (20mm for main lines, 16mm for branches) instead of PVC for hot water lines. Always install water hammer arrestors at washing machine and dishwasher connections. For G+2 and above, design separate pressure zones per floor.', 'plumbing', true, 'wrench'),
('የሞላሻ እና የቀለም ምርጫ ምርጥ ልምዶች', 'Tile and Paint Selection: Ethiopian Climate Considerations', 'For Ethiopian homes, select tiles with water absorption rate below 3% for bathrooms and below 5% for living areas. Porcelain tiles (available from local manufacturers like Kana) offer better durability than ceramic. For exterior paint, use 100% acrylic — it handles UV exposure and the Keremt rain cycle better than vinyl-acrylic. Apply two coats of primer and two finish coats for optimal coverage.', 'finishing', true, 'palette'),
('የግንባታ ቦታ ደህንነት ምርጥ ልምዶች', 'Construction Site Safety: Essential Practices', 'Every construction site in Ethiopia must have: hard hats for all workers, safety harnesses for work above 2m, proper scaffolding (not makeshift bamboo platforms), first aid kit with antivenom, and fire extinguishers. Designate a safety officer for sites with more than 20 workers. The cost of safety equipment is less than 1% of total project cost but prevents losses that can exceed 10% of project value.', 'structural', true, 'hard-hat');

-- Market prices seed data
INSERT INTO market_prices (material_am, material_en, unit, price, change_percent, category, updated_at) VALUES
('ዲርባ ሲሚንቶ (OPC)', 'Derba Cement (OPC)', 'Quintal', 8200, 3.5, 'cement', '2024-11-15'),
('ሙገር ሲሚንቶ (OPC)', 'Mugher Cement (OPC)', 'Quintal', 7800, 5.2, 'cement', '2024-11-14'),
('ዳንጎት ሲሚንቶ (PPC)', 'Dangote Cement (PPC)', 'Quintal', 7500, -1.8, 'cement', '2024-11-15'),
('አብሽሪ ሲሚንቶ', 'Habesha Cement (PPC)', 'Quintal', 7200, 2.1, 'cement', '2024-11-13'),
('የግራድ 60 ራብር 12ሚሜ', 'Grade 60 Rebar 12mm', 'Quintal', 14500, 7.3, 'steel', '2024-11-15'),
('የግራድ 60 ራብር 16ሚሜ', 'Grade 60 Rebar 16mm', 'Quintal', 14200, 6.8, 'steel', '2024-11-15'),
('የግራድ 40 ራብር 10ሚሜ', 'Grade 40 Rebar 10mm', 'Quintal', 12800, 4.5, 'steel', '2024-11-14'),
('የግራድ 60 ራብር 20ሚሜ', 'Grade 60 Rebar 20mm', 'Quintal', 14000, 5.9, 'steel', '2024-11-15'),
('የአዋሽ ወንዝ አሸዋ', 'Awash River Sand', 'Cubic Meter', 4500, -2.3, 'aggregate', '2024-11-12'),
('የተሰነጠቀ ድንግዝ', 'Crushed Stone (Base)', 'Cubic Meter', 6800, 1.5, 'aggregate', '2024-11-13'),
('የተሰነጠቀ ድንግዝ (ኮንክሪት)', 'Crushed Stone (Concrete)', 'Cubic Meter', 7200, 2.0, 'aggregate', '2024-11-14'),
('የዩካሊፕተስ እንጨት', 'Eucalyptus Timber 4x4', 'Piece', 850, 8.5, 'wood', '2024-11-10'),
('የቀርጤ እንጨት', 'Plywood Sheet 18mm', 'Sheet', 3200, 3.2, 'wood', '2024-11-11'),
('የሞላሻ ሰሌዳ 60x60', 'Porcelain Tile 60x60cm', 'Square Meter', 850, -0.5, 'finishing', '2024-11-15'),
('የውጪያ ሰዳሪ ስራ', 'Electrical Wiring (2.5mm²)', 'Meter', 35, 12.0, 'electrical', '2024-11-15');

-- Listings seed data
INSERT INTO listings (listing_type, title_am, title_en, description, price, location, contact_phone, contact_email, images, is_verified, is_urgent, category) VALUES
('property_sale', 'በቦሌ አዲስ G+2 ቤት', 'New G+2 House in Bole', 'Modern G+2 house with 4 bedrooms, 3 bathrooms, parking for 2 cars. Finished with premium materials. Ready to move in.', 8500000, 'Bole, Addis Ababa', '+251911234567', 'info@yebetweg.com', ARRAY['/listing/bole-house.jpg'], true, false, 'property'),
('property_sale', 'በሲሚት ለመሸጥ G+1 ቤት', 'G+1 House for Sale in CMC', 'Well-maintained G+1 house with garden, 3 bedrooms, 2 bathrooms. Quiet residential area near CMC hospital.', 5200000, 'CMC, Addis Ababa', '+251922345678', 'info@yebetweg.com', ARRAY['/listing/cmc-house.jpg'], true, false, 'property'),
('property_rent', 'በካዛንቺስ 3 መኝታ ኪራይ', '3BR Apartment for Rent in Kazanchis', 'Fully furnished 3-bedroom apartment with city view. Modern kitchen, 24/7 security, parking available.', 35000, 'Kazanchis, Addis Ababa', '+251933456789', 'info@yebetweg.com', ARRAY['/listing/kazanchis-apt.jpg'], true, true, 'property'),
('property_rent', 'በላፍቶ 2 መኝታ ኪራይ', '2BR Apartment for Rent in Lafto', 'Comfortable 2-bedroom apartment in new building. Close to main road, shopping centers.', 18000, 'Lafto, Addis Ababa', '+251944567890', 'info@yebetweg.com', ARRAY['/listing/lafto-apt.jpg'], false, false, 'property'),
('land_sale', 'በሌቡ 200 ሜትር ስኩዌር መሬት', '200sqm Land in Lebu', 'Prime residential land in fast-developing Lebu area. All utilities available. Perfect for G+3 construction.', 3500000, 'Lebu, Addis Ababa', '+251955678901', 'info@yebetweg.com', ARRAY['/listing/lebu-land.jpg'], true, false, 'property'),
('material_sale', 'ዲርባ ሲሚንቶ ለሽያጭ', 'Derba Cement Wholesale', 'Bulk Derba OPC cement available at competitive prices. Minimum order 50 quintals. Delivery available in Addis Ababa.', 7800, 'Merkato, Addis Ababa', '+251911789012', 'supplier@yebetweg.com', ARRAY['/listing/cement.jpg'], true, false, 'material'),
('material_sale', 'የግራድ 60 ራብር ለሽያጭ', 'Grade 60 Rebar Wholesale', 'Quality Grade 60 rebar in all sizes (8mm-25mm). Mill test certificates available. Bulk discount for orders above 100 quintals.', 14000, 'Akaki Kality, Addis Ababa', '+251922890123', 'steel@yebetweg.com', ARRAY['/listing/rebar.jpg'], true, true, 'material'),
('material_sale', 'የተለያዩ የኤሌክትሪክ ስራ ቁሶች', 'Electrical Materials Package', 'Complete electrical materials package for G+2 house: wires, switches, distribution board, conduits. Quality brands: Legrand, ABB.', 85000, 'Merkato, Addis Ababa', '+251933901234', 'electrical@yebetweg.com', ARRAY['/listing/electrical.jpg'], false, false, 'material'),
('material_sale', 'የሞላሻ እና የግድግዳ ቁሶች', 'Tiles and Finishing Materials', 'Wide selection of porcelain and ceramic tiles, paint, and finishing materials. Showroom visits available. Delivery within 24hrs in Addis.', 0, 'Kality, Addis Ababa', '+251944012345', 'tiles@yebetweg.com', ARRAY['/listing/tiles.jpg'], true, false, 'material'),
('professional_service', 'የአርክቴክቸር ዲዛይን አገልግሎት', 'Architectural Design Services', 'Complete architectural design for residential and commercial buildings. 3D visualization, permit drawings, and construction supervision included. 15+ years experience in Addis Ababa.', 150000, 'Bole, Addis Ababa', '+251911123456', 'arch@yebetweg.com', ARRAY['/listing/architect.jpg'], true, false, 'service'),
('professional_service', 'የመሐንዲስ ምርመራ አገልግሎት', 'Structural Engineering Consultation', 'Professional structural engineering services. Soil investigation, structural analysis, and construction quality control. Licensed by Ethiopian Engineers Association.', 80000, 'CMC, Addis Ababa', '+251922234567', 'eng@yebetweg.com', ARRAY['/listing/engineer.jpg'], true, false, 'service'),
('professional_service', 'የቧንቧ እና የኤሌክትሪክ ስራ ተቋም', 'Plumbing & Electrical Contracting', 'Licensed plumbing and electrical contracting firm. Complete installation for residential buildings. 1-year warranty on all work. References available.', 50000, 'Megenagna, Addis Ababa', '+251933345678', 'contractor@yebetweg.com', ARRAY['/listing/plumber.jpg'], true, true, 'service');

-- Professionals seed data
INSERT INTO professionals (name, specialty, rating, experience_years, location, phone, email, is_verified) VALUES
('Eng. Dawit Amare', 'engineer', 4.8, 18, 'Bole, Addis Ababa', '+251911123456', 'dawit@yebetweg.com', true),
('Arch. Tigist Haile', 'architect', 4.9, 12, 'CMC, Addis Ababa', '+251922234567', 'tigist@yebetweg.com', true),
('Ato Bezabih Girma', 'contractor', 4.6, 22, 'Megenagna, Addis Ababa', '+251933345678', 'bezabih@yebetweg.com', true),
('W/rt Hiwot Tadesse', 'electrician', 4.7, 8, 'Kazanchis, Addis Ababa', '+251944456789', 'hiwot@yebetweg.com', true),
('Ato Samuel Assefa', 'plumber', 4.5, 15, 'Lafto, Addis Ababa', '+251955567890', 'samuel@yebetweg.com', true),
('Ato Fikadu Bekele', 'surveyor', 4.8, 10, 'Ayat, Addis Ababa', '+251966678901', 'fikadu@yebetweg.com', true);

-- Ads seed data
INSERT INTO ads (advertiser, image_url, link, position, is_active) VALUES
('Ethiopian Construction Materials Corp', '/ads/ecmc-banner.jpg', 'https://example.com/ecmc', 'leaderboard', true),
('Addis Steel & Rebar Supply', '/ads/addis-steel.jpg', 'https://example.com/addis-steel', 'sidebar', true),
('Modern Homes Real Estate', '/ads/modern-homes.jpg', 'https://example.com/modern-homes', 'native_card', true);
